name: generate-pdf
on: 
  push:
    tags:
      - '*'
jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@master
      - name: Generate PDF
        run: ./generate-pdf.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "William Kray *.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.THIS_REPO_TOKEN }}
